services:
  - type: web
    name: sarkopeni-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_test:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
